version: "3"

services:
  cypherapp_demo:
    environment:
      - "TRACING=1"
      - "CYPHERNODE_URL=https://gatekeeper:${GATEKEEPER_PORT}"
    build:
      context: ./build
    image: cyphernode/cypherapp_demo
    volumes:
      - "$GATEKEEPER_DATAPATH/certs/cert.pem:/data/cert.pem"
      - "$GATEKEEPER_DATAPATH/keys.properties:/data/keys.properties"
      - "$GATEKEEPER_DATAPATH/htpasswd:/htpasswd/htpasswd"
    ports:
      - "3000:5173" # Map port 3000 on the host to 5173 in the container
    networks:
      - cyphernodeappsnet
    restart: always
    labels:
      - "traefik.docker.network=cyphernodeappsnet"
      - "traefik.frontend.redirect.entryPoint=https"
      - "traefik.frontend.rule=PathPrefixStrip:/cypherapp_demo"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.enable=true"
      - "traefik.port=9010"
      - "traefik.frontend.auth.basic.usersFile=/htpasswd/htpasswd"
    deploy:
      labels:
        - "traefik.docker.network=cyphernodeappsnet"
        - "traefik.frontend.redirect.entryPoint=https"
        - "traefik.frontend.rule=PathPrefixStrip:/cypherapp_demo"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.enable=true"
        - "traefik.port=9010"
        - "traefik.frontend.auth.basic.usersFile=/htpasswd/htpasswd"
      replicas: 1
      placement:
        constraints:
          - node.labels.io.cyphernode == true
      restart_policy:
        delay: 1s
      update_config:
        parallelism: 1
networks:
  cyphernodeappsnet:
    external: true
